const express = require("express")
const app = express()
require("./confing/database")
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
const cors = require("cors")
app.use(cors())
const userRouter = require("./Routes/useRoute")
const movieRouter = require("./Routes/movieRoute")
const membersRouter = require("./Routes/memberRoute")
const subscriptionRouter = require("./Routes/subscriptionRoute")
app.use("/users", userRouter)
app.use("/movies", movieRouter)
app.use("/members", membersRouter)
app.use("/subscription", subscriptionRouter)
app.listen(8001, () => {
    console.log("listening")
})